apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: eureka-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: "10%"
      maxSurge: "100%"
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      automountServiceAccountToken: false
      containers:
        - name: eureka-server
          image: twisted-fate:latest
          ports:
            - containerPort: 8761
          imagePullPolicy: Never
          readinessProbe:
            httpGet:
              path: /actuator/readiness
              port: 3000
            initialDelaySeconds: 180
            timeoutSeconds: 30
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 240
            timeoutSeconds: 30
          resources:
            requests:
              memory: "750Mi"
              cpu: "500m"
            limits:
              memory: "1000Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
spec:
  type: ClusterIP
  ports:
    - name: eureka-server
      port: 8761
      targetPort: 8761
  selector:
    app: eureka-server

